[PARAMS]

INPUT_FILE = '/mnt/sdb2/data/tests/cribriform_cases/misc/487/17A135_487_4M_HE/valid_glands_urls.csv'
NAME_COL = 'full_filename'
EMBEDDINGS_COL_0 = 'umap_sub_cluster_embeddings_0'
EMBEDDINGS_COL_1 = 'umap_sub_cluster_embeddings_1'
X_PX_COL = 'x_px'
Y_PX_COL = 'y_px'
URL_COL = 'url'
CLUSTER_COL = 'sub_cluster_h_labels'

